sudo: false
language: python
env:
  global:
  - secure: S/Qwufbvxf03AoBtb85ZP3mJUszLYixGN31M0EF9lcJA6csWT4wrBnuRpq0gyFAOYh5jXEkQEhmNfnL43xOHx5kZrDRbugaA63tZ8iuh3YngB3HVVCBom8qb1gE+MAWqHrzWcEMT+Q1AIbVqU9nsVt48p9hQRz+Lazz+pfKzuXM=
install:
- pip install pygments
- pip install mkdocs
- pip install mkdocs-material
script:
- git clean -f -d -x
after_success:
- git config user.name "Luiz Guilherme Silva"
- git config user.email "do.guilherme@hotmail.com"
- git remote add gh-token "https://${github_token}@github.com/desenho2019-1/docs.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
