site_name: Translate.me
extra_css: [extra.css]
nav:
  - Início: index.md
  - Documentos:
    - Metodologia: documentos/metodologia.md
    - Documento de Visão: documentos/doc_de_visao.md
    - Documento de Arquitetura: documentos/doc_de_arquitetura.md
    - Benchmarking: documentos/benchmarking.md
    - UML: documentos/uml.md
    - Identidade Visual: documentos/identidade_visual.md
  - Design Sprint: design_sprint.md
  - Requisitos:
    - Brainstorming: requisitos/brainstorming.md
    - NFRs: requisitos/doc_nfr.md
    - Tabela de Requisitos: requisitos/requisitos.md
  - Backlogs:
    - Backlogs Individuais:
      - Helena Backlog: backlogs/helena_backlog.md
      - Victor Backlog: backlogs/victor_backlog.md
      - Gabriela Backlog: backlogs/gabriela_backlog.md
      - Alexandre Backlog: backlogs/alexandre_backlog.md
      - Luiz Backlog: backlogs/luiz_backlog.md
      - Leticia Backlog: backlogs/leticia_introspeccao.md
      - Davi Backlog: backlogs/davi_backlog.md
      - Joao Backlog: backlogs/joao_backlog.md
    - Backlog Geral: backlogs/backlog_geral.md
  - Reuniões:
    - Reunião de Sprint:
      - Sprint 0: reunioes/sprints/sprint_0.md
    - Pontos de Controle:
      - PC 1: reunioes/pontos_de_controle/pc_1.md
      - PC 2: reunioes/pontos_de_controle/pc_2.md
      - PC 3: reunioes/pontos_de_controle/pc_3.md


  # - RASTREABILIDADE:
  #   - Rastros: rastreabilidade.md
  # - PRÉ-RASTREABILIDADE:
  #   - Argumentação: argumentacao.md
  #   - RichPicture: rich_picture.md
  # - ELICITAÇÃO DE REQUISITOS:
  #   - Análise de Discurso: analise_discurso.md
  #   - Análise de Protocolo: analise_protocolo.md
  #   - Entrevista: entrevista.md
  #   - Introspecção: introspeccao.md
  #   - Questionário: questionario.md
  #   - Storytelling: storytelling.md
  #   - Conclusão: conclusao_elicitacao.md
  # - MODELAGEM:
  #   - Cenários: cenarios.md
  #   - Léxicos: lexicos.md
  #   - Diagramas de Caso de Uso: diagramas_caso_uso.md
  #   - Especificações de Caso de Uso: especificacoes_caso_uso.md
  #   - Especificação Suplementar: especificacao_suplementar.md
  #   - Especificação Suplementar 2.0: especificacao_suplementar_2.md
  #   - Backlog do Produto: backlog.md
  #   - NFR: nfr.md
  #   - i*: iStar.md
  # - ANÁLISE:
  #   - NFR: analise_NFR.md
  #   - Pré-rastreabilidade: pre_rastreabilidade_analise.md
  #   - iStar: Istar_analise_inspecao.md
  #   - Caso de Uso: inspecao_caso_uso.md
  # - PÓS-RASTREABILIDADE:
  #   - Backward-From: backward_from.md
  #   - Forward-From: forward_from.md
theme:
    name: material
    language: 'pt'
    logo:
      icon: 'translate'
    palette:
      primary: 'cyan'
      accent: 'cyan'
    favicon: 'assets/images/favicon.ico'

repo_name: 'Translate.me'
repo_url: 'https://github.com/translate-me/translate-me/'
edit_uri: ''
