site_name: Translate.me
extra_css: [extra.css]
nav:
  - Início: index.md
  - Dinâmica e Seminário I:
    -  Design Sprint: def_tema.md
  - Dinâmica e Seminário II: metodologia.md
  - Dinâmica e Seminário III: 
    - UMLs estáticos: desenho_de_software/uml/uml_estaticos.md
  - Dinâmica e Seminário IV:
    - UMLs dinâmicos: desenho_de_software/uml/uml_dinamicos.md
  - Dinâmica e Seminário V: 
    - Parte A, GoFs: desenho_de_software/padroes/gof/seminarioParteA.md
    - Parte B, GoFs emergentes: desenho_de_software/padroes/gof/seminarioParteB.md
  - Iniciativas extras:
    - Documentos de Projeto:
      - Documento de Visão: documentos/projeto/doc_de_visao.md
      - Documento de Arquitetura: documentos/projeto/doc_de_arquitetura.md
      - Benchmarking: documentos/projeto/benchmarking.md
      - Identidade Visual: documentos/projeto/identidade_visual.md
    - Documentos de Gerência:
      - Goal Question Metric: documentos/gerencia/gqm.md
      - Política de Contribuição: documentos/gerencia/pol_contribuicao.md
      - Canvas: documentos/gerencia/canvas.md
      - Termo de Abertura do Projeto: documentos/gerencia/tap.md
    - Elicitação de requisitos:
      - Rich Picture: requisitos/elicitacao/rich_picture.md
      - Mapa Mental: requisitos/elicitacao/mapa_mental.md
      - Brainstorming: requisitos/elicitacao/brainstorming.md
      - Introspecção: requisitos/elicitacao/introspeccao.md
      - Protótipo: requisitos/elicitacao/prototipo.md
    - Modelagem:
      - Backlogs Individuais:
        - Victor Backlog: requisitos/modelagem/backlogs_individuais/victor_backlog.md
        - Gabriela Backlog: requisitos/modelagem/backlogs_individuais/gabriela_backlog.md
        - Alexandre Backlog: requisitos/modelagem/backlogs_individuais/alexandre_backlog.md
        - Luiz Backlog: requisitos/modelagem/backlogs_individuais/luiz_backlog.md
        - Davi Backlog: requisitos/modelagem/backlogs_individuais/davi_backlog.md
        - Joao Backlog: requisitos/modelagem/backlogs_individuais/joao_backlog.md
      - Backlog Geral: requisitos/modelagem/backlog_geral.md
      - NFR: requisitos/modelagem/nfr.md
      - Tabela de Requisitos: requisitos/tabela_requisitos.md
    - Estudo - padrões de Projeto:
      - GRASP: desenho_de_software/padroes/grasp.md
      - GoFs:
        - Criacionais: desenho_de_software/padroes/gof/criacionais.md
        - Estruturais: desenho_de_software/padroes/gof/estruturais.md
        - Comportamentais: desenho_de_software/padroes/gof/comportamentais.md
    - Arquitetura de Software:
      - Modelos: arquitetura_de_software/modelos.md
      - Padrões Arquiteturais: arquitetura_de_software/padroes_arquiteturais.md
    - Reuniões:
      - Reunião de Sprint:
        - Sprint 0: reunioes/sprints/sprint_0.md
        - Sprint 1: reunioes/sprints/sprint_1.md
        - Sprint 2: reunioes/sprints/sprint_2.md
        - Sprint 3: reunioes/sprints/sprint_3.md
        - Sprint 4: reunioes/sprints/sprint_4.md
        - Sprint 5: reunioes/sprints/sprint_5.md
      - Pontos de Controle:
        - PC 1: reunioes/pontos_de_controle/pc_1.md
        - PC 2: reunioes/pontos_de_controle/pc_2.md
        - PC 3: reunioes/pontos_de_controle/pc_3.md
        - PC 4: reunioes/pontos_de_controle/pc_4.md
#######################################################################################

theme:
    name: material
    language: 'pt'
    logo:
      icon: 'translate'
    palette:
      primary: 'cyan'
      accent: 'cyan'
    favicon: 'assets/images/favicon.ico'

repo_name: 'Translate.me'
repo_url: 'https://github.com/translate-me/translate-me/'
edit_uri: ''